Bump fms-extras version to avoid torch 2.3.0 issue (#82)
Torch 2.3.0 was released last week and fms-extras was pulling it in as a
build dependency, leading to symbol conflicts with torch 2.2.1 (what we
are using currently). I've changed the versioning inside fms-extras to
ensure this doesn't happen.

Just bumping version for fms-extras

Resolves ImportErrors that are present with current main:
```
 ImportError: /opt/tgis/lib/python3.11/site-packages/fms_extras/paged_c.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda14ExchangeDeviceEa
 ```

n/a

Signed-off-by: Thomas Parnell <tpa@zurich.ibm.com>